### ISSUE TITLE
No module named youtube_dl

### ISSUE THREAD

**Issue by bashmail** [tnt2402/pornhub_dl#1]
python pornhub_dl.py -h
Traceback (most recent call last):
  File "pornhub_dl.py", line 2, in <module>
    from lib_pornhub import *
  File "/home/user/pornhub_dl/lib_pornhub.py", line 2, in <module>
    import youtube_dl
ImportError: No module named youtube_dl

Even it is installed and working fine

**Comment by tnt2402** [comment]
Have u install youtube_dl with pip ?

**Comment by bashmail** [comment]
Requirement already satisfied: youtube-dl in /home/user/.local/lib/python3.7/site-packages (2021.12.17)

**Comment by bashmail** [comment]
I resolved the issue by adding PATH manually.

BTW, I forgot to mention that I am using WSL Ubuntu as well as Debian

**Comment by tnt2402** [comment]
Awesome, thanks!
