### ISSUE TITLE
BUG: AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bashmail** [tnt2402/pornhub_dl#2]
I am getting following error on random videos

user@rpi-8g:~/Desktop/pornhub_dl $ python pornhub_dl.py --url https://www.pornhub.com/view_video.php?viewkey=ph62ebe2772bc2b

########################################################

 ____                  _   _       _               _ _ 
|  _ \ ___  _ __ _ __ | | | |_   _| |__         __| | |
| |_) / _ \| '__| '_ \| |_| | | | | '_ \ _____ / _` | |
|  __/ (_) | |  | | | |  _  | |_| | |_) |_____| (_| | |
|_|   \___/|_|  |_| |_|_| |_|\__,_|_.__/       \__,_|_|
                                                       

                        Made by tnt2402

########################################################
Output directory: /home/hsn/Desktop/pornhub_dl\model\\
Traceback (most recent call last):
  File "/home/user/Desktop/pornhub_dl/pornhub_dl.py", line 39, in <module>
    main()
  File "/home/user/Desktop/pornhub_dl/pornhub_dl.py", line 35, in main
    ph_get_video(args.url)
  File "/home/user/Desktop/pornhub_dl/lib_pornhub.py", line 144, in ph_get_video
    model_name = get_model_name(url)
  File "/home/user/Desktop/pornhub_dl/lib_pornhub.py", line 122, in get_model_name
    name = finder. Find(class_='bolded').text.replace('\n', '').strip()
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by tnt2402** [comment]
Are u using any VPN ? Turn it on

**Comment by bashmail** [comment]
Yes, I am using NordVPN and it is on system wide

**Comment by tnt2402** [comment]
i fixed single file download mode now. U can test it again and tell me. Playlist mode havent been upload yet
